# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-github-repository
  description: Terraform Module to provision a GitHub Repository
  homepage: https://cloudposse.com/accelerate
  topics:
    - terraform
    - github
    - repository
    - automation
    - automation-as-code
    - ci/cd
